# -*- coding: utf-8 -*-
"""HYPERTENSION_CODE_FINAL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NBLppe1tCo6039Mm5P2sEDPJu3EYbiBa
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv("hypertension_dataset.csv")
df.head()

df.info()

df.describe()

df.isnull().sum()

df_filled = df.copy()

# Kategorikal
for col in df_filled.select_dtypes(include='object').columns:
  df_filled[col] = df_filled[col].fillna(df_filled[col].mode()[0])

# Numerikal
for col in df_filled.select_dtypes(include=[np.number]).columns:
  df_filled[col] = df_filled[col].fillna(df_filled[col].mean())

print(df_filled)

file_path = "/content/hypertension_dataset.csv"

df = pd.read_csv(file_path)

df.replace(np.nan, 0, inplace=True)

print("Jumlah Missing Value per Kolom")
print(df.isnull().sum())

print("\nBaris yang Mengandung Missing Value:")
print(df[df.isnull().any(axis=1)])

df_filled = df.copy()
for col in df_filled.select_dtypes(include=[np.number]).columns:
    df_filled[col] = df_filled[col].fillna(df_filled[col].median())

print("\nJumlah Missing Value per Kolom(setelah isi mean):")
print(df_filled.isnull().sum())

df_filled.to_csv("df_filled.csv", index=False)

df.dtypes

file_path = "/content/hypertension_dataset.csv"  # pastikan nama file benar
df = pd.read_csv(file_path)

# --- 3. Ganti tanda "-" jadi NaN dan ubah kolom numerik ke float ---
df.replace("-", np.nan, inplace=True)

# Pastikan kolom numerik benar-benar jadi angka
kolom_numerik = ["Age", "Salt_Intake", "Stress_Score", "Sleep_Duration", "BMI", ]
for col in kolom_numerik:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# --- 4. Hapus baris yang masih ada missing value ---
df_clean = df.dropna()

# --- 5. Deteksi Outlier dengan metode IQR + tampilkan bound ---
for col in kolom_numerik:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    print(f"\n📌 Analisis kolom: {col}")
    print(f"Q1 (25%)       : {Q1}")
    print(f"Q3 (75%)       : {Q3}")
    print(f"IQR            : {IQR}")
    print(f"Lower Bound    : {lower_bound}")
    print(f"Upper Bound    : {upper_bound}")

    # Data yang termasuk outlier
    outlier_rows = df_clean[(df_clean[col] < lower_bound) | (df_clean[col] > upper_bound)]
    print("\nOutlier ditemukan:")
    if outlier_rows.empty:
        print("Tidak ada outlier pada kolom ini.")
    else:
        print(outlier_rows[["Age", col, "Salt_Intake", "Stress_Score", "Sleep_Duration", "BMI"]])

# --- 6. Visualisasi Boxplot untuk setiap kolom numerik ---
plt.figure(figsize=(12, 8))
for i, col in enumerate(kolom_numerik, 1):
    plt.subplot(2, 3, i) # Changed from 2x2 to 2x3 to accommodate 5 plots
    sns.boxplot(y=df_clean[col], color="skyblue")
    plt.title(f"Boxplot {col}")
plt.tight_layout()
plt.show()

pd.get_dummies(data=df, columns=["BP_History", "Medication", "Family_History","Exercise_Level", "Smoking_Status", "Has_Hypertension" ], drop_first=True)

df_min_max_manual = df.copy()

min_numeric = df_min_max_manual['Age'].min()
min_numeric

max_numeric = df_min_max_manual['Age'].max()
max_numeric

df_min_max_manual['Age_norm'] = (df_min_max_manual['Age'] - min_numeric)/(max_numeric - min_numeric)
df_min_max_manual['Age_norm']

df = pd.read_csv('/content/hypertension_dataset.csv')
df.rename(columns={'salt_intake': 'salt'}, inplace=True)
df.to_csv('/content/hypertension_dataset2.csv', index=False)

min_numeric = df_min_max_manual['Salt_Intake'].min()
min_numeric

max_numeric = df_min_max_manual['Salt_Intake'].max()
max_numeric

df_min_max_manual['Salt_Intake_norm'] = (df_min_max_manual['Salt_Intake'] - min_numeric)/(max_numeric - min_numeric)
df_min_max_manual['Salt_Intake_norm']

df_clean.to_csv("data_clean.csv", index=False)

# 1️⃣ Import pustaka dasar
import pandas as pd

# 2️⃣ Contoh: baca dataset kamu (ganti path dengan file kamu di Colab)
# Misal kamu upload file bernama 'data_hipertensi.csv'
df = pd.read_csv('/content/hypertension_dataset.csv')

# 3️⃣ Tampilkan 5 data pertama untuk memastikan strukturnya
print("Data sebelum konversi:")
print(df.head())

# 4️⃣ Cek nilai unik dalam kolom 'Hipertensi'
print("\nNilai unik sebelum diubah:")
print(df['Has_Hypertension'].unique())

# 5️⃣ Ubah nilai kolom 'Hipertensi' menjadi numerik:
# Misalnya 'Yes' -> 1 dan 'No' -> 0
df['Has_Hypertension'] = df['Has_Hypertension'].map({'Yes': 1, 'No': 0})

# 6️⃣ Tampilkan hasil setelah konversi
print("\nData setelah konversi:")
print(df.head())

# 7️⃣ Simpan hasilnya jika ingin
df.to_csv('/content/hypertension_dataset_konversi.csv', index=False)
print("\nFile berhasil disimpan sebagai: data_hipertensi_konversi.csv")

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

X = df[['Age', 'Salt_Intake']]
y = df['Has_Hypertension']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# Import library yang dibutuhkan
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Contoh: membaca dataset milikmu
# Pastikan file CSV kamu di-upload di Google Colab atau Google Drive
df = pd.read_csv("hypertension_dataset_konversi.csv")

# Tampilkan 5 baris pertama
print("Data sebelum normalisasi:")
print(df.head())

# Inisialisasi scaler
scaler = MinMaxScaler()

# Pilih kolom numerik yang akan dinormalisasi
kolom_numerik = ['Age', 'Salt_Intake']

# Lakukan normalisasi
df[kolom_numerik] = scaler.fit_transform(df[kolom_numerik])

print("\nData setelah normalisasi:")
print(df.head())

# Simpan hasil normalisasi ke file baru (opsional)
df.to_csv("data_hipertensi_normalized.csv", index=False)

# Import library
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Pisahkan fitur dan target
X = df[['Age', 'Salt_Intake']]
y = df['Has_Hypertension']   # pastikan kolom target sudah berupa 0 dan 1

# Split data menjadi data latih dan uji
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inisialisasi model
model = LogisticRegression()

# Latih model
model.fit(X_train, y_train)

# Prediksi data uji
y_pred = model.predict(X_test)

# Evaluasi model
print("Akurasi model:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nLaporan Klasifikasi:\n", classification_report(y_test, y_pred))

# Lihat koefisien model
coef_df = pd.DataFrame({
    'Variabel': ['Age', 'Salt_Intake'],
    'Koefisien': model.coef_[0]
})
print("\nKoefisien Model:\n", coef_df)

# Import library
import pandas as pd
from scipy.stats import chi2_contingency

# Contoh: memuat data kamu
df = pd.read_csv('/content/data_hipertensi_normalized.csv')  # ganti dengan nama file kamu

# --- 1. Kategorisasi Umur ---
df['Age_Group'] = pd.cut(df['Age'], bins=[0, 30, 50, 100], labels=['<30', '30-50', '>50'])

# --- 2. Kategorisasi Asupan Garam ---
df['Salt_Level'] = pd.cut(df['Salt_Intake'], bins=[0, 5, 7, 20], labels=['Rendah', 'Sedang', 'Tinggi'])

# --- 3. Tabel kontingensi dan uji Chi-Square ---

# Hubungan antara umur dan hipertensi
table_age = pd.crosstab(df['Age'], df['Has_Hypertension'])
chi2_age, p_age, dof_age, expected_age = chi2_contingency(table_age)

# Hubungan antara asupan garam dan hipertensi
table_salt = pd.crosstab(df['Salt_Intake'], df['Has_Hypertension'])
chi2_salt, p_salt, dof_salt, expected_salt = chi2_contingency(table_salt)

print("=== Uji Chi-Square Hubungan Umur dengan Hipertensi ===")
print(table_age)
print(f"Chi-Square: {chi2_age:.4f}, p-value: {p_age:.4f}")

print("\n=== Uji Chi-Square Hubungan Asupan Garam dengan Hipertensi ===")
print(table_salt)
print(f"Chi-Square: {chi2_salt:.4f}, p-value: {p_salt:.4f}")

df.to_csv("hypertension_final.csv", index=False)